### PR TITLE
Add 3 R packages

### PR DESCRIPTION
**Pull request by Bikingman**
This repository is a great resource! I looked it over and thought that I'd offer my 2cents and suggest adding stplanr, tidyverse, and r5r to the list of valuable R packages for transportation planning and modeling. I took a quick look around the Other Technology Resource Aggregators pages and didn't see any of them readily listed. This also eliminates a number of trailing spaces.

### CODE REVIEW

**Comment by d-wasserman** [comment]
Our lint checks can't run with the existing conflicts. Can you resolve them? Also can you break up the contributions so that you only contribute to one section at a time?

**Comment by Bikingman** [comment]
Thanks, @d-wasserman - Resolved the conflicts - a few resources were added since I forked. 

Can you clarify what you mean by, 'break up the contributions so that you only contribute to one package per commit?' Do you mean one resource per commit? Or in other words, should I commit all three R packages over three separate commits?

**Comment by d-wasserman** [comment]
You have format changes entangled with your contributions, and commit titles that don't specify which did what. We have been trying to limit contributions to one commit at a time. #37 is an example.

If the three r package additions can have a clear commit message , that would help.

**Comment by Bikingman** [comment]
Ah, sounds good. I thought those format changes only removed trailing spaces (done automatically by my IDE). I'll update the commits

**Comment by d-wasserman** [comment]
I might suggest opening a new PR.

I appreciate the the format updates BTW, but I just want to isolate contributions and format changes.

It also boosts your contribution count! For what that is worth.

**Comment by Bikingman** [comment]
Will do!

**Pull request closed without merging**
